title: The BrownBlog
author: @TheRealBrownDog
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  TheRealBrownDog's blogosphere where he can share things dog, bikes
  and Seagull. If you don't know what that means, hang around and
  take a look and see.

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-minimal
